ALTER TABLE PRODUCT ADD CONSTRAINT fk_product FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(id) ON DELETE CASCADE;
ALTER TABLE PRODUCT ADD CONSTRAINT fk_product2 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(id) ON DELETE CASCADE;

ALTER TABLE REVENUE ADD CONSTRAINT fk_revenue FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(id) ON DELETE CASCADE;

ALTER TABLE STOCK ADD CONSTRAINT fk_stock FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(id) ON DELETE CASCADE;
ALTER TABLE STOCK ADD CONSTRAINT fk_stock2 FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(id) ON DELETE CASCADE;

ALTER TABLE ORDER_TABLE ADD CONSTRAINT fk_order2 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(id) ON DELETE CASCADE;

ALTER TABLE ORDER_DETAIL ADD CONSTRAINT fk_order_detail FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(id) ON DELETE CASCADE;
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT fk_order_detail2 FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE(id) ON DELETE CASCADE;